### ISSUE TITLE
Another runtime error

### ISSUE THREAD

**Issue by ice1000** [10XL/codewars-voter#2]
```
err.class: Selenium::WebDriver::Error::TimeOutError

id: 582d4d98e302387481000ef1, Exception: timed out after 5 seconds (no such element: Unable to locate element: {"method":"class name","selector":"vote-assessment"}
  (Session info: chrome=60.0.3112.90)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Linux 4.10.0-30-generic x86_64))
```

**Comment by 10XL** [comment]
It could be because codewars is being slow and the page didn't load in 5 seconds(default timeout) or because you authored the kata but it doesn't show up in the [`code-challenges/authored` endpoint](https://www.codewars.com/api/v1/users/ice1000/code-challenges/authored). It's not the second case since you didn't author [that kata](https://www.codewars.com/kata/bf-reverse-input/).  _After_ the script is done voting, when the chromedriver instance(s) close, these get logged to '/user_data/:username/*_failed.json' so you can manually check those katas. Codewars is pretty slow right now, you could try changing to preview.codewars.com but I'm not sure if your points will update.

In the cases where a user completes katas before voting on all previous katas or the script doesn't complete, these are a couple of features that I plan to add;
  - Asynchronously updating the json as katas are voted on.
  - Updating a user's json data instead of re-downloading and not utilizing the already voted on katas.

**Comment by ice1000** [comment]
I saw pages on the chromes opened by the voter, it's not logged in. I've already added my token to the path, what's wrong?

**Comment by 10XL** [comment]
Token should be added to an environment variable called `CODEWARS_TOKEN`, not the path. Try supplying the token explicitly with `-t "tokenValue"`. 
I think it's because codewars is slow right now, try changing `https://www.codewars.com` to `http://preview.codewars.com` at [lib/voter.rb#L22](https://github.com/10XL/codewars-voter/blob/master/lib/voter.rb#L22) and [lib/voter.rb#L59](https://github.com/10XL/codewars-voter/blob/master/lib/voter.rb#L59).

**Comment by ice1000** [comment]
I've changed it and it's still like that. I did add it into `CODEWARS_TOKEN`. And I'm not logged in.

**Comment by ice1000** [comment]
I tried again. I'm using

```
ice1000@ice1000:~/git-repos/codewars-voter$ ruby vote.rb -u ice1000 -i 3 -f "user_data/ice1000/2017-08-09-21-38-07.json" -t "my token"
```

And still not logged in. Is there any other possible ways to log in?

**Comment by 10XL** [comment]
Can you open a new chrome window in incognito mode and manually add the cookie to check if it logs you in?

**Comment by ice1000** [comment]
Let me try

**Comment by ice1000** [comment]
I still can't log in. Could you provide some alternative ways to log in? Like, open the browser, and let me log in manually, and tell your tool, and then it starts voting.

**Comment by 10XL** [comment]
You could do that by changing [Voter#setup_browser](https://github.com/10XL/codewars-voter/blob/master/lib/voter.rb#L20) to:
```ruby
  def setup_browser
    browser = Selenium::WebDriver.for :chrome
    browser.navigate.to "http://preview.codewars.com/users/#{@user.name}"
    # browser.manage.add_cookie(:name => "remember_user_token", :value => @token)
    # pause to login
    puts "login and press enter to continue!"
    gets
    browser
  end
```

**Comment by ice1000** [comment]
Thank you

**Comment by ice1000** [comment]
Well...

```
/usr/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
        from /usr/lib/ruby/2.3.0/net/protocol.rb:136:in `readuntil'
        from /usr/lib/ruby/2.3.0/net/protocol.rb:146:in `readline'
        from /usr/lib/ruby/2.3.0/net/http/response.rb:40:in `read_status_line'
        from /usr/lib/ruby/2.3.0/net/http/response.rb:29:in `read_new'
...
        from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/common/search_context.rb:62:in `find_element'
        from /home/ice1000/git-repos/codewars-voter/lib/voter.rb:56:in `block (3 levels) in vote'
        from /var/lib/gems/2.3.0/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/common/wait.rb:56:in `until'
        from /home/ice1000/git-repos/codewars-voter/lib/voter.rb:56:in `block (2 levels) in vote'
```

Any idea..

**Comment by 10XL** [comment]
Looks like a timeout, just try switching to`preview.codewars.com` everywhere in `lib/voter.rb`, `lib/voter/kata.rb`, and `lib/voter/user.rb`.

Also with the change to `setup_browser` above, you have to log in to each browser instance and then press enter however many instances there are in the terminal to continue.

**Comment by ice1000** [comment]
Thanks.
